COMMENT ON TABLE stone IS 'ENUM with Domino stones';
COMMENT ON TABLE placement IS 'ENUM with placement of stones';
COMMENT ON TABLE game_status IS 'ENUM with status of a game session';
COMMENT ON TABLE users IS 'Users that have used the system to play Domino';
COMMENT ON COLUMN users.name IS 'Name of the user';
COMMENT ON TABLE game_session IS 'Games of Domino that have been played or are currently occuring';
COMMENT ON COLUMN game_session.game_status_id IS 'Current status of this Game Session';
COMMENT ON COLUMN tstamp IS 'Time in which the Game Session started';
COMMENT ON TABLE player IS 'Players that participate in a particular game of Domino';
COMMENT ON COLUMN player.user_id IS 'The player that participates';
COMMENT ON COLUMN player.game_session_id IS 'The game session in which the player participates';
COMMENT ON TABLE player_has_stone IS 'Stones initially in the hand of a player in a particular game session';
COMMENT ON COLUMN player_has_stone.user_id IS 'User that has stones';
COMMENT ON COLUMN player_has_stone.game_session_id IS 'Game session in which the user has stones';
COMMENT ON COLUMN player_has_stone.stone_id IS 'Stone that the user has';
COMMENT ON TABLE game_state_diff IS 'A change on the state of the game';
COMMENT ON COLUMN game_state_diff.game_session_id IS 'Game session being affected';
COMMENT ON COLUMN game_state_diff.version IS 'The version of the game state, used to ensure chronological updates';
COMMENT ON COLUMN game_state_diff.user_id IS 'User that made the action that caused the change';
COMMENT ON COLUMN game_state_diff.stone_id IS 'Stone that was played';
COMMENT ON COLUMN game_state_diff.placement_id IS 'Where the stone was placed';
COMMENT ON COLUMN game_state_diff.tstamp IS 'Moment in which the play was made';
